// <auto-generated />
using System;
using CaprezzoDigitale.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaprezzoDigitale.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220715223752_add-notifications")]
    partial class addnotifications
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Allegato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<long>("MessaggioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MessaggioId");

                    b.ToTable("Allegati");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.BollettinoArpa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PDF_FileName")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.Property<string>("XML_FileName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BollettiniArpa");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Guid")
                        .HasColumnType("text");

                    b.Property<string>("Messaggio")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Keys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .HasColumnType("text");

                    b.Property<string>("P256dh")
                        .HasColumnType("text");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId")
                        .IsUnique();

                    b.ToTable("SubscriptionKeys");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Messaggio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataPubblicazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sottotitolo")
                        .HasColumnType("text");

                    b.Property<string>("Testo")
                        .HasColumnType("text");

                    b.Property<short>("TipoMessaggioId")
                        .HasColumnType("smallint");

                    b.Property<string>("Titolo")
                        .HasColumnType("text");

                    b.Property<string>("UrlImmagineCopertina")
                        .HasColumnType("text");

                    b.Property<string>("UrlPdfImmagineCopertina")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TipoMessaggioId");

                    b.ToTable("Messaggi");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Statistica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Guid")
                        .HasColumnType("text");

                    b.Property<short>("TipoStatisticaId")
                        .HasColumnType("smallint");

                    b.Property<string>("Valore")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TipoStatisticaId");

                    b.ToTable("Statistiche");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .HasColumnType("text");

                    b.Property<string>("ExpirationTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.TipoMessaggio", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Colore")
                        .HasColumnType("text");

                    b.Property<string>("Descrizione")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Icona")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipiMessaggio");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.TipoStatistica", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipiStatistica");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Allegato", b =>
                {
                    b.HasOne("CaprezzoDigitale.WebApi.Models.Messaggio", "Messaggio")
                        .WithMany("Allegati")
                        .HasForeignKey("MessaggioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Messaggio");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Keys", b =>
                {
                    b.HasOne("CaprezzoDigitale.WebApi.Models.Subscription", null)
                        .WithOne("Keys")
                        .HasForeignKey("CaprezzoDigitale.WebApi.Models.Keys", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Messaggio", b =>
                {
                    b.HasOne("CaprezzoDigitale.WebApi.Models.TipoMessaggio", "TipoMessaggio")
                        .WithMany("Messaggi")
                        .HasForeignKey("TipoMessaggioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoMessaggio");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Statistica", b =>
                {
                    b.HasOne("CaprezzoDigitale.WebApi.Models.TipoStatistica", "TipoStatistica")
                        .WithMany("Statistiche")
                        .HasForeignKey("TipoStatisticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoStatistica");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Messaggio", b =>
                {
                    b.Navigation("Allegati");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.Subscription", b =>
                {
                    b.Navigation("Keys");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.TipoMessaggio", b =>
                {
                    b.Navigation("Messaggi");
                });

            modelBuilder.Entity("CaprezzoDigitale.WebApi.Models.TipoStatistica", b =>
                {
                    b.Navigation("Statistiche");
                });
#pragma warning restore 612, 618
        }
    }
}
